### PR TITLE
Release/1.2.1

### LINKED ISSUE #126: Release version 1.2.1
This issue is for tracking changes for the 1.2.1 release.  Target release date: **TBD December 2021**.

### Pre-release steps
- [ ] IDEAL: add/update screenshot files and references in readme.txt/README.md for new functionality

### [Release steps](https://github.com/10up/simple-podcasting/blob/develop/CONTRIBUTING.md#release-instructions)

- [x] Branch: Starting from `develop`, cut a release branch named `release/1.2.1` for your changes.
- [x] Version bump: Bump the version number in `maps-block-apple.php`, `readme.txt`, `package-lock.json`, and `package.json` if it does not already reflect the version being released.  Update both the plugin "Version:" property and the plugin `MAPS_BLOCK_APPLE_VERSION` constant in `maps-block-apple.php`.
- [x] Changelog: Add/update the changelog in `CHANGELOG.md` and `readme.txt`.
- [x] Props: update `CREDITS.md` with any new contributors, confirm maintainers are accurate.
- [x] New files: Check to be sure any new files/paths that are unnecessary in the production version are included in `.distignore`.
- [x] Readme updates: Make any other readme changes as necessary. `README.md` is geared toward GitHub and `readme.txt` contains WordPress.org-specific content.  The two are slightly different.
- [x] Merge: Make a non-fast-forward merge from your release branch to `develop` (or merge the pull request), then do the same for `develop` into `trunk` (`git checkout trunk && git merge --no-ff develop`). `trunk` contains the latest stable release.
- [x] Test: Run through common tasks while on `trunk` to be sure it functions correctly.
- [x] Push: Push your `trunk` branch to GitHub (e.g. `git push origin trunk`).
- [x] Release: Create a [new release](https://github.com/10up/simple-podcasting/releases/new), naming the tag and the release with the new version number, and targeting the `trunk` branch. Paste the changelog from `CHANGELOG.md` into the body of the release and include a link to the [closed issues on the milestone](https://github.com/10up/simple-podcasting/milestone/7?closed=1).
- [x] SVN: Wait for the [GitHub Action](https://github.com/10up/simple-podcasting/actions) to finish deploying to the WordPress.org repository. If all goes well, users with SVN commit access for that plugin will receive an emailed diff of changes.
- [x] Check WordPress.org: Ensure that the changes are live on https://wordpress.org/plugins/simple-podcasting/. This may take a few minutes.
- [x] Close the milestone: Edit the [milestone](https://github.com/10up/simple-podcasting/milestone/7) with release date (in the `Due date (optional)` field) and link to GitHub release (in the `Description` field), then close the milestone.
- [x] Punt incomplete items: If any open issues or PRs which were milestoned for `1.2.1` do not make it into the release, update their milestone to `1.3.0`, or `Future Release`.

### PR DESCRIPTION
**Pull request by cadic**
### Description of the Change

Release and version bump to 1.2.1.
Closes #126 

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by jeffpaul** [comment]
@cadic one question, should we add `/assets` to `.distignore` since the plugin builds the `/dist` directory as part of the build/release process ([see WP.org SVN](https://plugins.trac.wordpress.org/browser/simple-podcasting/trunk))?

**Comment by jeffpaul** [comment]
WP latest e2e passed, waiting on WP 4.6 and WP trunk.

**Comment by cadic** [comment]
@jeffpaul thank you, I agree, `/assets` should be in `.distignore`, we are safe since all JS/CSS are enqueued from the `dist` folder.

**Comment by cadic** [comment]
@jeffpaul `minimum` and `trunk` tests are still waiting. Could it be related to this:

We have 3 core testing in the matrix for **push develop/trunk**
https://github.com/10up/simple-podcasting/blob/bb1485bfc635c4e1238e06ed62b6a4a0ac1a7065/.github/workflows/test-branch.yml#L3-L19

But only one core (latest) for **pull-request develop**
https://github.com/10up/simple-podcasting/blob/bb1485bfc635c4e1238e06ed62b6a4a0ac1a7065/.github/workflows/test-pr.yml#L3-L16

So for the PR from `release/1.2.1` to `deploy` just the first test has been run, but 3 expected?

**Comment by jeffpaul** [comment]
@dinhtungdu as you helped add the e2e tests here, what's your take on @cadic's analysis above?

**Comment by jeffpaul** [comment]
Ok @dinhtungdu confirmed that:
> The branch one only tests the push event to `develop` or `trunk` with three different WP version. The PR one tests PR only against the latest WP production

so it sounds like the branch tests should not be included as a PR check, I've removed those in the repo and we look good now.

**Review by jeffpaul — APPROVED** [review]
@cadic let me know if you want to jump on a zoom together to pair on the final release process steps or if they're documented well enough you feel comfortable running through them yourself.  The biggest item I would call out is to note specifically where branches are referred to (`trunk`, `develop`) as those need to be precise on each step.

**Pull request merged**
