### PR TITLE
Fully clear new term form after submission #33

### PR DESCRIPTION
**Pull request by turtlepod**
Fully clear new term form after submission #33

### CODE REVIEW

**Comment by turtlepod** [comment]
Let me know if "master" is not the correct target branch

**Comment by helen** [comment]
@turtlepod PRs should be against `develop` :)

**Comment by helen** [comment]
I changed the base branch here in GH but you will need to refresh it to resolve the conflicts.

**Comment by turtlepod** [comment]
Thank you @helen 
Branch updated.

**Comment by turtlepod** [comment]
@ryanwelcher I updated the branch. Let me know if it's not working as expected.

**Comment by ryanwelcher** [comment]
@turtlepod works as expected! @helen wondering if you can take a look at the experience but code look good to me!

**Comment by helen** [comment]
Looks good to me too, will commit the built files post-merge

**Pull request merged**
