### PR TITLE
Release 1.4.0

### LINKED ISSUE #210: Release 1.4.0
This issue is for tracking changes for the 1.4.0 release.  Target release date: **6 January 2023**.

### Pre-release steps
- [ ] IDEAL: add/update screenshot files and references in readme.txt/README.md for new functionality

### [Release steps](https://github.com/10up/simple-podcasting/blob/develop/CONTRIBUTING.md#release-instructions)

- [x] Branch: Starting from `develop`, cut a release branch named `release/1.4.0` for your changes.
- [x] Version bump: Bump the version number in `simple-podcasting.php`, `package-lock.json`, `package.json`, and `readme.txt` if it does not already reflect the version being released.  Update both the plugin "Version:" property and the plugin `PODCASTING_VERSION` constant in `simple-podcasting.php`.
- [x] Changelog: Add/update the changelog in both `CHANGELOG.md` and `readme.txt`.
- [x] Props: update `CREDITS.md` with any new contributors, confirm maintainers are accurate.
- [x] New files: Check to be sure any new files/paths that are unnecessary in the production version are included in `.distignore`.
- [x] Readme updates: Make any other readme changes as necessary. `README.md` is geared toward GitHub and `readme.txt` contains WordPress.org-specific content. The two are slightly different.
- [x] Merge: Make a non-fast-forward merge from your release branch to `develop` (or merge the pull request), then do the same for `develop` into `trunk` (`git checkout trunk && git merge --no-ff develop`). `trunk` contains the latest stable release.
- [x] Test: Run through common tasks while on `trunk` to be sure it functions correctly. Don't forget to build.
- [x] Push: Push your `trunk` branch to GitHub (e.g. `git push origin trunk`).
- [x] Test the pre-release ZIP locally by downloading it from the **Build release zip** action artifact to ensure the plugin doesn't break after release.
- [x] Release: Create a [new release](https://github.com/10up/simple-podcasting/releases/new), naming the tag and the release with the new version number, and targeting the `trunk` branch.  Paste the changelog from `CHANGELOG.md` into the body of the release and include a link to the [closed issues on the milestone](https://github.com/10up/simple-podcasting/milestone/8?closed=1).
- [x] SVN: Wait for the [GitHub Action](https://github.com/10up/simple-podcasting/actions) to finish deploying to the WordPress.org repository. If all goes well, users with SVN commit access for that plugin will receive an emailed diff of changes.
- [x] Check WordPress.org: Ensure that the changes are live on https://wordpress.org/plugins/simple-podcasting/. This may take a few minutes.
- [x] Close the milestone: Edit the [milestone](https://github.com/10up/simple-podcasting/milestone/8) with release date (in the `Due date (optional)` field) and link to GitHub release (in the `Description` field), then close the milestone.
- [x] Punt incomplete items: If any open issues or PRs which were milestoned for `1.4.0` do not make it into the release, update their milestone to `1.5.0`, or `Future Release`.

### PR DESCRIPTION
**Pull request by cadic**
### Description of the Change
Release and version bump 1.4.0

Closes #210 

### Verification Process

Verified manually via VS Code

### Checklist:

- [ ] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by jeffpaul — DISMISSED** [review]
Looks good, though one question of whether there are updated (or new) screenshots that should be included with this release?

**Comment by jeffpaul** [comment]
I'm fine with handling the release and then coming back after to fix the release dates in CHANGELOG.md and readme.txt with whatever the eventual release date is.  No need to re-submit PR for approval just to change those for release.

**Comment by cadic** [comment]
> Looks good, though one question of whether there are updated (or new) screenshots that should be included with this release?

According to the changelog, we don't have any breaking changes or new features worth documenting with screenshots.

But in the future update, we definitely want to update screenshots:
- We now have "Type of show" dropdown, need to be updated on screenshot-3.png
- We have the "Classic" edit post screen on the screenshot-1.png. Need to add Block Editor screenshot as well (and update classic screenshot to the latest default theme colour palette). Or replace the classic screenshot with the block.

**Comment by cadic** [comment]
Added a new issue #213

**Comment by cadic** [comment]
@jeffpaul I've added last-minute security update and changed the release date, I know it wasn't expected, appreciate your quick review again.

**Review by jeffpaul — DISMISSED** [review]
looks good, thanks for handling the release!

**Review by Sidsector9 — APPROVED** [review]

**Pull request merged**
