### PR TITLE
Feature/issue 83 latest episode block

### LINKED ISSUE #83: Block Pattern: Latest Episode Block
**Is your enhancement related to a problem? Please describe.**
With the advent of [Block Patterns](https://wptavern.com/block-patterns-will-change-everything), we might want to consider a simple block pattern to cover the Latest Episode Block concept.

**Describe the solution you'd like**

- [ ] Pulls in latest episode automatically, might have some options for setting image override, etc but essentially will get all data from podcast.

**Designs**

TBD, but ideal to help shape what we'd craft

**Describe alternatives you've considered**

n/a

**Additional context**

[Block Pattern creation walkthroughs](https://melchoyce.design/2020/03/30/creating-a-simple-block-pattern-plugin-for-the-gutenberg-editor/) from the super rad @melchoyce.

### PR DESCRIPTION
**Pull request by barneyjeffries**
### Description of the Change

Added variation based on Query Loop for Latest Episode

Closes [#83](https://github.com/10up/simple-podcasting/issues/83)

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Credits

Props @

### CODE REVIEW

**Comment by faisal-alvi** [comment]
@barneyjeffries thanks for the PR, can you please check the PHPCS issues and fix it?

https://github.com/10up/simple-podcasting/actions/runs/7397681115/job/20125248325

**Review by faisal-alvi — CHANGES_REQUESTED** [review]
I will continue the review after the PHPCS issues are addressed, thanks!

**Comment by barneyjeffries** [comment]
@faisal-alvi yes of course - sorry meant to check these before

**Comment by faisal-alvi** [comment]
@barneyjeffries thanks for the fixes, the cypress test if failing for the WP minimum. I tried re-running the test but it failed again. Can you please check?

https://github.com/10up/simple-podcasting/actions/runs/7477805060/job/20488930685

**Review by faisal-alvi — COMMENTED** [review]
_waiting until cypress tests pass_

**Comment by barneyjeffries** [comment]
@faisal-alvi @jeffpaul  I think we should pause on CR for this PR as I'm working on the Player enhancements which will supersede this change.

**Comment by barneyjeffries** [comment]
@faisal-alvi @jeffpaul  Apologies, I got confused with the 'Listen Time' task - this task is not related to the Player Enhancements. 

I will into the tests and why they are failing.

**Comment by barneyjeffries** [comment]
@faisal-alvi @jeffpaul I've run the tests locally and the block test is working correctly - I have had this before with Cypress, but I don't think anything in this PR should have affected these existing tests.

**Review by faisal-alvi — APPROVED** [review]
LGTM, thanks for working on this.

## BE:

image


## FE:

image

**Pull request merged**
