### PR TITLE
Synchronized Podcasting Categories

### LINKED ISSUE #173: Add Subcategories
### Is your enhancement related to a problem? Please describe.

It would be useful to add sub-categories for each category chosen for a Podcast. The full list is at https://podcasters.apple.com/support/1691-apple-podcasts-categories. 

### Designs

_No response_

### Describe alternatives you've considered

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by zamanq**
### Requirements
The requirements can be found [here](https://github.com/10up/simple-podcasting/issues/173)

### Description of the Change

The categories and sub-categories lists are synchronized based on the latest list provided by Apple here https://podcasters.apple.com/support/1691-apple-podcasts-categories

### Possible Drawbacks

None so far.

### Verification Process
The updated list can be checked by going to the podcasting admin menu page and then scrolling through the Categories drop-downs.

updated categories

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Changelog Entry

> Updated - Podcasting Categories and Sub-Categories

### Credits

Props @zamanq @jeffpaul

### CODE REVIEW

**Comment by dkotter** [comment]
@zamanq Thanks for the PR! I have no issues with the code but there is something to consider and not sure best way to solve. With this change, quite a few categories are either removed entirely or at least renamed. For any existing podcasts that have been set up using one or more of these categories (either directly or using a sub-category where the parent is now changed), those categories will no longer be output at all.

I'm worried this may be unexpected behavior for any existing users of this plugin and if there's a way we could still support existing categories, that would be great. I know that may be difficult though as I don't think we want to continue allowing users to choose categories that Apple no longer supports, but would be great if we could still support any existing podcasts for backwards compatibility

**Comment by zamanq** [comment]
@dkotter Hi, yes this is something that I discussed with @jeffpaul earlier before adding the updated categories. He and I prepared a list of categories that can be added/updated in the plugin and @jeffpaul provided me with the curated list of categories to be added which are then added on the plugin. @jeffpaul Can you please share your thoughts on this as well?

**Comment by dkotter** [comment]
So what I was thinking is maintaining a list of deprecated categories, similar to our `get_podcasting_categories` method we have right now. These would be referenced when we render the categories in the RSS feed, so we validate those categories against both `get_podcasting_categories` and `get_podcasting_deprecated_categories` (or similar).

But I guess a question I'm not sure on. If someone is currently using `Games & Hobbies` as a category (which is now `Leisure`) or `Government & Organizations` (which is now `Government`), how does Apple treat those? Do those podcasts just not show up anywhere right now? Or are they smart enough on their end to forward those along to the new categories? If they're just not showing up at all anymore, I think that gives us more freedom to just make these changes and not worry as much, since being in no categories would be the same as being in categories Apple isn't supporting. I would hope though that Apple still supports those categories in some way.

In either case, I think we also need something in the release notes/readme to make it clear that approved categories are changing and users should double check the categories their podcasts are assigned to.

**Comment by jeffpaul** [comment]
I concur that we should have a callout in the changelog/release notes about these changes, perhaps providing a link to the old/new lists of categories, so that folks can check their categories to ensure they're what they desire/intend.

**Review by cadic — APPROVED** [review]

**Pull request merged**
