### PR TITLE
Add: devcontainer support

### PR DESCRIPTION
**Pull request by dinhtungdu**
### Description of the Change

This PR adds [dev container](https://code.visualstudio.com/docs/remote/containers) configuration for Visual Studio Code Remote Development feature. This is the preparation for supporting Github Codespaces in the future as well.

At the moment, we have:
- A webserver to run WordPress powered by Nginx, php-fpm and Maria DB.
- Auto WordPress installation, available at `http://localhost:8080`
- Auto dependencies installation.
- Project-wise definition, just copy-n-paste to another project to get devcontainer up and running.

What I'm considering:
- ~Support WPAcceptance Test.~
- Support .env variables to config and custom the environment, such as toggling xDebug, changing port... ~> Done!

The limitations:
- Currently, I don't have access to Github Codespaces, so I don't know how it handles the WordPress URL on Codespaces.
- ~Can't push to Github inside the dev container.~

### CODE REVIEW

**Comment by helen** [comment]
Playing around with this in the Codespaces environment and there is an environment variable we should be able to use: `SITE_HOST=https://${CODESPACE_NAME}-8080.githubpreview.dev`

However, that doesn't seem to be available yet in `createEnv.sh`, and `docker-compose.yml` doesn't seem to be able to read the variables set in `createEnv.sh`. Going to keep tinkering with this here and there, but not sure what's going to happen with Codespaces for OSS so it's not a high priority. Certainly not higher than E2E testing :)

**Comment by helen** [comment]
Screen Shot 2021-09-02 at 9 34 27 PM

I went in and set the `WP_HOME` and `WP_SITEURL` constants in `/var/www/html/wp-config.php` from VSCode in the Codespace and it works!! I still think we should be able to set the site URL properly during install, but oddly it cannot connect to the DB in `setup.sh` despite being able to install when you navigate to the site... `setup.log` here: https://gist.github.com/helen/08314ccbc76bc750b244ce2d8f8ba376

**Comment by helen** [comment]
It works now! I moved the `wp install` part to after the Node setup/dependency installation, which is not truly reliable, but it does seem to give it enough time for the DB to come up and be able to connect. There is probably some better way to do this, like keep trying the DB and waiting for it to come up or something, but this is super exciting :)

**Comment by jeffpaul** [comment]
@dinhtungdu did you want to resurrect this here and try to get back on proving this as an option for our OSP projects?

**Comment by dinhtungdu** [comment]
@jeffpaul I'm closing this to focus on #121 which uses the official WordPress images instead of 10up custom ones.

**Pull request closed without merging**
