### PR TITLE
Feature: Cancel edit mode

### PR DESCRIPTION
**Pull request by Firestorm980**
### Description of the Change

Adds the ability for the user to edit their podcasting selection without going into the current "editor" mode and losing their currently selected podcast.

### Alternate Designs

Using a custom toggle with the current editor mode and a "cancel" button.

### Benefits

- Allows the user to edit their media selection without losing their current selection if they decide to cancel
- Aligns with the same editing pattern as the core audio block for consistency with WP core

### Possible Drawbacks

May be initially confusing if a user/editor is used to the current paradigm of editing.

### Verification Process

1. Create a new podcast block
2. Add a media file
3. Click the "Replace" dropdown
4. Click "Media Library" to replace file, abort
5. Confirm the media wasn't replaced
6. Click "Media Library", replace file
7. Confirm the file was replaced

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [x] All new and existing tests passed.

### Applicable Issues

#62 

#### Removed
- Editing mode
#### Added
- Core `MediaReplaceFlow` to edit the podcast media

### CODE REVIEW

**Review by dinhtungdu — CHANGES_REQUESTED** [review]
@Firestorm980 the replacement is a great UX enhancement, it worked perfectly in my test.

There is a small issue on deleting the podcast block, the podcast meta still remains in the post meta table.

**Comment by Firestorm980** [comment]
> There is a small issue on deleting the podcast block, the podcast meta still remains in the post meta table.

@dinhtungdu I tried deleting a block locally on the `develop` branch (not this feature) and confirmed none of the meta was removed (caption, duration, filesize, etc.) from the post. So it seems unrelated to this specific feature. I think it may be better to potentially make a new issue for this.

**Review by dinhtungdu — APPROVED** [review]

**Comment by jeffpaul** [comment]
@Firestorm980 there are a couple merge conflicts after merging in your separate PR.  Mind helping resolve the conflicts here so we can get this merged in?

**Comment by Firestorm980** [comment]
@jeffpaul Updated. Should be good to go.

**Pull request merged**
